#!/bin/bash
#############################################################
# Name:        Supportconfig Plugin for SUSE Enterprise Storage
# Description: Gathers important troubleshooting information
#              about SUSE Enterprise Storage
# License:     GPLv2
# Author:      Tim Serong <tserong@suse.com>
# Modified:    2015-02-13
#############################################################

SVER=1.0.0
RCFILE="/usr/lib/supportconfig/resources/scplugin.rc"
LOG_LINES=5000  # 0 means include the entire file

[ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }

# Helper functions liberated from Matt Barringer's supportutils-plugin-susecloud
validate_rpm_if_installed() {
    thisrpm="$1"
    echo "#==[ Validating RPM ]=================================#"
    if rpm -q "$thisrpm" >/dev/null 2>&1; then
        echo "# rpm -V $thisrpm"

        if rpm -V "$thisrpm"; then
            echo "Status: Passed"
        else
            echo "Status: WARNING"
        fi
    else
        echo "package $thisrpm is not installed"
        echo "Status: Skipped"
    fi
    echo
}

#############################################################
section_header "Supportconfig Plugin for SUSE Enterprise Storage, v${SVER}"
rpm_list=/usr/lib/supportconfig/resources/ses-rpm-list
for thisrpm in $(cat "$rpm_list"); do
    validate_rpm_if_installed "$thisrpm"
done

#############################################################
section_header "Ceph cluster status"

if [ -x /usr/bin/ceph ]; then
    plugin_command "ceph -s"
    plugin_command "ceph mon dump"
    plugin_command "ceph osd tree"
fi

#############################################################
section_header "Ceph config"

if [ -d /etc/ceph ]; then
    if files=$(find /etc/ceph -type f | egrep -v '.keyring$'); then
        if [ -n "$files" ]; then
            pconf_files $files
        fi
    fi
fi

#############################################################
section_header "Ceph log files"

plog_files $LOG_LINES /var/log/ceph/*.log

#############################################################
section_header "Calamari log files"

plog_files $LOG_LINES /var/log/calamari/*.log

#############################################################
section_header "Salt config"

if [ -d /etc/salt ]; then
    if files=$(find /etc/salt -type f | egrep -v '.pem$'); then
        if [ -n "$files" ]; then
            pconf_files $files
        fi
    fi
fi

#############################################################
section_header "Salt log files"

plog_files $LOG_LINES /var/log/salt/{master,minion}

