.TH ses-plugin "8" "13 Feb 2015" "ses-plugin" "Support Utilities Manual"
.SH NAME
ses-plugin \- SUSE Enterprise Storage Plugin for
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This plugin extends supportconfig's functionality to include SUSE Enterprise Storage
information. Supportconfig saves the plugin output as plugin-ses.txt.

.SH FILES
.I /usr/lib/supportconfig/plugins/ses
.RS
The SUSE Enterprise Storage plugin
.RE
.SH AUTHOR
Tim Serong <tserong@suse.com>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via:
.B http://bugzilla.suse.com
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
